# Generated by Django 2.2.6 on 2019-11-07 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims101', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='index101',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='index101',
            name='data_one',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='FT'),
        ),
        migrations.AlterField(
            model_name='index101',
            name='data_two',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='DT'),
        ),
    ]
