# Generated by Django 2.2.6 on 2019-11-07 21:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sims101', '0002_auto_20191107_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index101Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=6, verbose_name='Province')),
                ('canton', models.CharField(max_length=6, verbose_name='Canton')),
                ('parroquia', models.CharField(max_length=6, verbose_name='Parroquia')),
                ('code', models.CharField(max_length=6, verbose_name='CODE')),
                ('data_one', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='FT')),
                ('data_two', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='DT')),
                ('data_three', models.IntegerField(verbose_name='PT')),
                ('calculated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='NPFD')),
                ('yearly', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sims101.Index101')),
            ],
        ),
    ]
