# Generated by Django 2.2.6 on 2019-11-08 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sims101', '0003_index101data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index101data',
            name='yearly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backdata', to='sims101.Index101'),
        ),
    ]
