# Generated by Django 2.2.6 on 2019-11-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='index_name',
            field=models.CharField(max_length=200, verbose_name='index name'),
        ),
        migrations.AlterField(
            model_name='description',
            name='sequence',
            field=models.CharField(choices=[('101', '101'), ('102', '102'), ('103', '103'), ('104', '104'), ('105', '105'), ('106', '106'), ('107', '107'), ('108', '108'), ('109', '109'), ('110', '110')], max_length=3, unique=True, verbose_name='sequence'),
        ),
    ]
