# Generated by Django 2.2.6 on 2019-11-05 20:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_auto_20191105_1539'),
        ('sims102', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index102',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_one', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='FT')),
                ('data_two', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='PT')),
                ('calculated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='NF')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.Description')),
            ],
            options={
                'ordering': ['id'],
                'permissions': [('index102_contributor', 'index102_contributor'), ('index102_validator', 'index102_validator')],
            },
        ),
        migrations.DeleteModel(
            name='Index101',
        ),
    ]
